/*
 * Clinical Match API
 * A simple API to match patients to clinical trials.
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Location;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ClinicalTrialMatch
 */
public class ClinicalTrialMatchTest {
    private final ClinicalTrialMatch model = new ClinicalTrialMatch();

    /**
     * Model tests for ClinicalTrialMatch
     */
    @Test
    public void testClinicalTrialMatch() {
        // TODO: test ClinicalTrialMatch
    }

    /**
     * Test the property 'trialId'
     */
    @Test
    public void trialIdTest() {
        // TODO: test trialId
    }

    /**
     * Test the property 'trialName'
     */
    @Test
    public void trialNameTest() {
        // TODO: test trialName
    }

    /**
     * Test the property 'locations'
     */
    @Test
    public void locationsTest() {
        // TODO: test locations
    }

    /**
     * Test the property 'summary'
     */
    @Test
    public void summaryTest() {
        // TODO: test summary
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
