/*
 * Clinical Match API
 * A simple API to match patients to clinical trials.
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Location;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ClinicalTrialMatch
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-18T19:57:05.929993-05:00[America/New_York]", comments = "Generator version: 7.10.0")
public class ClinicalTrialMatch {
  public static final String SERIALIZED_NAME_TRIAL_ID = "trialId";
  @SerializedName(SERIALIZED_NAME_TRIAL_ID)
  @javax.annotation.Nonnull
  private String trialId;

  public static final String SERIALIZED_NAME_TRIAL_NAME = "trialName";
  @SerializedName(SERIALIZED_NAME_TRIAL_NAME)
  @javax.annotation.Nonnull
  private String trialName;

  public static final String SERIALIZED_NAME_LOCATIONS = "locations";
  @SerializedName(SERIALIZED_NAME_LOCATIONS)
  @javax.annotation.Nonnull
  private List<Location> locations = new ArrayList<>();

  public static final String SERIALIZED_NAME_SUMMARY = "summary";
  @SerializedName(SERIALIZED_NAME_SUMMARY)
  @javax.annotation.Nonnull
  private String summary;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private String status;

  public ClinicalTrialMatch() {
  }

  public ClinicalTrialMatch trialId(@javax.annotation.Nonnull String trialId) {
    this.trialId = trialId;
    return this;
  }

  /**
   * The unique identifier of the clinical trial
   * @return trialId
   */
  @javax.annotation.Nonnull
  public String getTrialId() {
    return trialId;
  }

  public void setTrialId(@javax.annotation.Nonnull String trialId) {
    this.trialId = trialId;
  }


  public ClinicalTrialMatch trialName(@javax.annotation.Nonnull String trialName) {
    this.trialName = trialName;
    return this;
  }

  /**
   * The name of the clinical trial
   * @return trialName
   */
  @javax.annotation.Nonnull
  public String getTrialName() {
    return trialName;
  }

  public void setTrialName(@javax.annotation.Nonnull String trialName) {
    this.trialName = trialName;
  }


  public ClinicalTrialMatch locations(@javax.annotation.Nonnull List<Location> locations) {
    this.locations = locations;
    return this;
  }

  public ClinicalTrialMatch addLocationsItem(Location locationsItem) {
    if (this.locations == null) {
      this.locations = new ArrayList<>();
    }
    this.locations.add(locationsItem);
    return this;
  }

  /**
   * Get locations
   * @return locations
   */
  @javax.annotation.Nonnull
  public List<Location> getLocations() {
    return locations;
  }

  public void setLocations(@javax.annotation.Nonnull List<Location> locations) {
    this.locations = locations;
  }


  public ClinicalTrialMatch summary(@javax.annotation.Nonnull String summary) {
    this.summary = summary;
    return this;
  }

  /**
   * Detailed description of the clinical trial
   * @return summary
   */
  @javax.annotation.Nonnull
  public String getSummary() {
    return summary;
  }

  public void setSummary(@javax.annotation.Nonnull String summary) {
    this.summary = summary;
  }


  public ClinicalTrialMatch status(@javax.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * Status about the clinical trial
   * @return status
   */
  @javax.annotation.Nullable
  public String getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClinicalTrialMatch clinicalTrialMatch = (ClinicalTrialMatch) o;
    return Objects.equals(this.trialId, clinicalTrialMatch.trialId) &&
        Objects.equals(this.trialName, clinicalTrialMatch.trialName) &&
        Objects.equals(this.locations, clinicalTrialMatch.locations) &&
        Objects.equals(this.summary, clinicalTrialMatch.summary) &&
        Objects.equals(this.status, clinicalTrialMatch.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(trialId, trialName, locations, summary, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClinicalTrialMatch {\n");
    sb.append("    trialId: ").append(toIndentedString(trialId)).append("\n");
    sb.append("    trialName: ").append(toIndentedString(trialName)).append("\n");
    sb.append("    locations: ").append(toIndentedString(locations)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("trialId");
    openapiFields.add("trialName");
    openapiFields.add("locations");
    openapiFields.add("summary");
    openapiFields.add("status");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("trialId");
    openapiRequiredFields.add("trialName");
    openapiRequiredFields.add("locations");
    openapiRequiredFields.add("summary");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ClinicalTrialMatch
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ClinicalTrialMatch.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ClinicalTrialMatch is not found in the empty JSON string", ClinicalTrialMatch.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ClinicalTrialMatch.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ClinicalTrialMatch` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ClinicalTrialMatch.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("trialId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `trialId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("trialId").toString()));
      }
      if (!jsonObj.get("trialName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `trialName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("trialName").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("locations").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `locations` to be an array in the JSON string but got `%s`", jsonObj.get("locations").toString()));
      }

      JsonArray jsonArraylocations = jsonObj.getAsJsonArray("locations");
      // validate the required field `locations` (array)
      for (int i = 0; i < jsonArraylocations.size(); i++) {
        Location.validateJsonElement(jsonArraylocations.get(i));
      };
      if (!jsonObj.get("summary").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `summary` to be a primitive type in the JSON string but got `%s`", jsonObj.get("summary").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ClinicalTrialMatch.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ClinicalTrialMatch' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ClinicalTrialMatch> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ClinicalTrialMatch.class));

       return (TypeAdapter<T>) new TypeAdapter<ClinicalTrialMatch>() {
           @Override
           public void write(JsonWriter out, ClinicalTrialMatch value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ClinicalTrialMatch read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ClinicalTrialMatch given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ClinicalTrialMatch
   * @throws IOException if the JSON string is invalid with respect to ClinicalTrialMatch
   */
  public static ClinicalTrialMatch fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ClinicalTrialMatch.class);
  }

  /**
   * Convert an instance of ClinicalTrialMatch to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

